[package]
name = "blockchain-store"
version = "0.1.0"
authors = ["Tamas Blummer <tamas.blummer@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/rust-bitcoin/rust-blockchain-store/"
repository = "https://github.com/rust-bitcoin/rust-blockchain-store/"
documentation = "https://github.com/rust-bitcoin/rust-blockchain-store/"
description = "Persistent blockchain store and a convenience library for a blockchain"
keywords = [ "crypto", "bitcoin" ]
readme = "README.md"

[lib]
name = "blockchain_store"
path = "src/lib.rs"

[dependencies]
log = "0.4"
bitcoin="0.13"


[dev-dependencies]
simple_logger = "0.5.0"
rand="0.5"
hex = "0.3"
