[package]
name = "bcdb"
version = "0.1.0"
authors = ["Tamas Blummer <tamas.blummer@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/rust-bitcoin/rust-blockchain-store/"
repository = "https://github.com/rust-bitcoin/rust-blockchain-store/"
documentation = "https://github.com/rust-bitcoin/rust-blockchain-store/"
description = "Persistent blockchain store and a convenience library for a blockchain"
keywords = [ "blockchain", "bitcoin" ]
readme = "README.md"

[lib]
name = "bcdb"
path = "src/lib.rs"

[features]
bitcoin_support=["bitcoin"]

[dependencies]
log = "0.4"
rand="0.5"
siphasher = "0.2"
byteorder="1"
simple_logger = "0.5.0"
bitcoin={version="0.13", optional=true}

[dev-dependencies]
hex = "0.3"
